### PR TITLE
fix: fix checkout views

### LINKED ISSUE #902: UI fix for 'your cart is empty' view
### Summary

The info about empty cart is not aligned, the same with the button 'go back to store'. I suggest to use all space available on the page instead of splitting page. Or centre the info to the left 
image

### Steps to reproduce

1. Add 3 items to the basket 
2. Go to checkout 
3. In checkout set quantity to 0 for all items 
Result:
Screenshot 2023-10-06 at 12 47 25

The info about empty cart is not aligned, the same with the button 'go back to store'.

### A link to a reproduction repository

_No response_

### Output from envinfo

_No response_

### PR DESCRIPTION
**Pull request by grzegorzpokorski**
Fixes #902 issue.

Changes: 
1. Fix checout background.

2. Fix empty cart page view in checkout:

3. Fix not found page view in checkout:

### CODE REVIEW

File: src/checkout/sections/Summary/Summary.tsx [hunk 1]
```diff
@@ -39,7 +40,12 @@ export const Summary: FC<SummaryProps> = ({
 	discount,
 }) => {
 	return (
-		<div className="flex h-fit w-full flex-col overflow-hidden rounded lg:overflow-visible">
+		<div
+			className={clsx(
+				"z-0 flex h-fit w-full flex-col overflow-hidden rounded lg:overflow-visible",
+				"before:bottom-0 before:left-auto before:right-0 before:top-0 before:z-[-1] before:w-[calc(50%)] before:border-l before:border-neutral-200 before:bg-neutral-50 before:content-[''] before:lg:fixed",
```
Comment (grzegorzpokorski) [inline src/checkout/sections/Summary/Summary.tsx:46]:
```suggestion
				"before:bottom-0 before:left-auto before:right-0 before:top-0 before:z-[-1] before:w-1/2 before:border-l before:border-neutral-200 before:bg-neutral-50 before:content-[''] before:lg:fixed",
```

**Review by zaiste — APPROVED** [review]

File: src/checkout/components/ErrorContentWrapper.tsx [hunk 2]
```diff
@@ -0,0 +1,13 @@
+import { type ReactNode } from "react";
+
+type Props = {
+	children: ReactNode;
+};
+
+export const ErrorContentWrapper = ({ children }: Props) => {
+	return (
+		<div className="mx-auto flex max-w-screen-sm flex-col items-center gap-y-4 bg-neutral-50 px-8 py-16 text-center">
+			<>{children}</>
```
Comment (mmiszy) [inline src/checkout/components/ErrorContentWrapper.tsx:10]: This fragment is redundant: we can just use `{children}`

File: src/checkout/sections/Summary/Summary.tsx [hunk 3]
```diff
@@ -39,7 +40,12 @@ export const Summary: FC<SummaryProps> = ({
 	discount,
 }) => {
 	return (
-		<div className="flex h-fit w-full flex-col overflow-hidden rounded lg:overflow-visible">
+		<div
+			className={clsx(
+				"z-0 flex h-fit w-full flex-col overflow-hidden rounded lg:overflow-visible",
```
Comment (mmiszy) [inline src/checkout/sections/Summary/Summary.tsx:45]: I believe setting the overflow here doesn't do much? So we can skip both `overflow-hidden` and `overflow-visible`

File: src/checkout/sections/Summary/Summary.tsx [hunk 4]
```diff
@@ -39,7 +40,12 @@ export const Summary: FC<SummaryProps> = ({
...
+				"before:bottom-0 before:left-auto before:right-0 before:top-0 before:z-[-1] before:w-1/2 before:border-l before:border-neutral-200 before:bg-neutral-50 before:content-[''] before:lg:fixed",
```
Comment (mmiszy) [inline src/checkout/sections/Summary/Summary.tsx:46]: We can avoid rendering the `before` pseudoelement at all before it's needed – `before:lg:content-['']`

Comment (mmiszy) [inline src/checkout/sections/Summary/Summary.tsx:46]: Both `right-0` and `w-1/2` seems to be redundant

Comment (mmiszy) [inline src/checkout/sections/Summary/Summary.tsx:46]: Instead of adding custom `z-[-1]` we could use builtin -10: `-z-10`

File: src/app/checkout/page.tsx [hunk 5]
```diff
@@ -17,16 +17,16 @@ export default function CheckoutPage({
 	}
 
 	return (
-		<div className="checkout-bg min-h-[100dvh]">
```
Comment (mmiszy) [inline src/app/checkout/page.tsx:20]: We can also delete the `checkout-bg` class from a CSS file.

**Review by mmiszy — COMMENTED** [review]
Thanks for your another amazing contribution! I've added some comments if you want to know what I'd change (but your implementation is also great, it's just small nudges).
I also pushed the changes here, I hope you don't mind: https://github.com/saleor/storefront/commit/e793100974125bfc18c4d979d8c73bc557170328

**Comment by grzegorzpokorski** [comment]
> Thanks for your another amazing contribution! I've added some comments if you want to know what I'd change (but your implementation is also great, it's just small nudges). I also pushed the changes here, I hope you don't mind: [e793100](https://github.com/saleor/storefront/commit/e793100974125bfc18c4d979d8c73bc557170328)

Thank you for the kind words! I'll try to provide changes this evening.

**Comment by grzegorzpokorski** [comment]
> > Thanks for your another amazing contribution! I've added some comments if you want to know what I'd change (but your implementation is also great, it's just small nudges). I also pushed the changes here, I hope you don't mind: [e793100](https://github.com/saleor/storefront/commit/e793100974125bfc18c4d979d8c73bc557170328)
> 
> Thank you for the kind words! I'll try to provide changes this evening.

Oh, I missed the most important information that you just implemented changes 🤦‍♂️ It's good that you're always vigilant about the quality of the PR 💪

**Comment by zaiste** [comment]
@mmiszy 's vigilance can be also positively overwhelming at times ;)
